package simx.components.physics.jbullet.ontology

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

package object types{
  def init(){}
	object Acceleration extends simx.core.ontology.SVarDescription(simx.components.physics.jbullet.ontology.types.Vector3 as simx.core.ontology.Symbols.acceleration definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/physiscs/SimxPhysics.owl#Acceleration")
	
	object Gravity extends simx.core.ontology.SVarDescription(simx.components.physics.jbullet.ontology.types.Vector3 as simx.core.ontology.Symbols.gravity definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/physiscs/SimxPhysics.owl#Gravity")
	
	object HalfExtends extends simx.core.ontology.SVarDescription(simx.components.physics.jbullet.ontology.types.Vector3 as simx.core.ontology.Symbols.halfExtends definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/concepts/BasicTypes.owl#HalfExtends")
	
	object Impulse extends simx.core.ontology.SVarDescription(simx.components.physics.jbullet.ontology.types.Vector3 as simx.core.ontology.Symbols.impulse definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/physiscs/SimxPhysics.owl#Impulse")
	
	object Normal extends simx.core.ontology.SVarDescription(simx.components.physics.jbullet.ontology.types.Vector3 as simx.core.ontology.Symbols.normal definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/concepts/BasicTypes.owl#Normal")
	
	object Transformation extends simx.core.ontology.SVarDescription(simx.core.ontology.types.Transformation as simx.core.ontology.Symbols.transformation withType classOf[com.bulletphysics.linearmath.Transform] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/SimxCoreOntology.owl#Transformation")
	
	object Vector3 extends simx.core.ontology.SVarDescription(simx.core.ontology.types.Vector3 as simx.core.ontology.Symbols.vector3 withType classOf[javax.vecmath.Vector3f] definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/concepts/BasicTypes.owl#Vector3")
	object Velocity extends simx.core.ontology.SVarDescription(simx.components.physics.jbullet.ontology.types.Vector3 as simx.core.ontology.Symbols.velocity definedAt "http://www.hci.uni-wuerzburg.de/ontologies/simx/components/physiscs/SimxPhysics.owl#Velocity")
}